Repository jannomeister/ncov-tracker, pull requests merged in 2020-03, with the labels that each got.

#8 refactor(graph): use other source of api
  package.json
  src/components/DayChart.vue
Labels: enhancement

#10 feat: added total PUMs report
  src/components/Report.vue
Labels: enhancement

#11 feat: added total PUIs and Tested report
  src/components/Report.vue
Labels: enhancement

#13 feat(graph): added graph for age and gender
  src/components/AgeChart.vue
  src/components/Dashboard.vue
Labels: enhancement

#15 feat: added sidebar news and info
  src/components/Dashboard.vue
  src/components/Report.vue
  src/components/sidebar/SideBar.vue
  src/components/sidebar/Urgent.vue
Labels: enhancement

#16 feat: added nmmc hospital needs
  src/components/sidebar/Urgent.vue
Labels: enhancement

#18 feat(pw): added pwa support
  package-lock.json
  package.json
  public/img/icons/android-chrome-192x192.png
  public/img/icons/android-chrome-512x512.png
  public/img/icons/android-chrome-maskable-192x192.png
  public/img/icons/android-chrome-maskable-512x512.png
  public/img/icons/apple-touch-icon-120x120.png
  public/img/icons/apple-touch-icon-152x152.png
  public/img/icons/apple-touch-icon-180x180.png
  public/img/icons/apple-touch-icon-60x60.png
  public/img/icons/apple-touch-icon-76x76.png
  public/img/icons/apple-touch-icon.png
  public/img/icons/favicon-16x16.png
  public/img/icons/favicon-32x32.png
  public/img/icons/msapplication-icon-144x144.png
  public/img/icons/mstile-150x150.png
  public/img/icons/safari-pinned-tab.svg
  public/robots.txt
  src/main.js
  src/registerServiceWorker.js
  vue.config.js
Labels: enhancement

#19 feat(graph): added tabs and by month graph
  src/components/Dashboard.vue
  src/components/Footer.vue
  src/components/charts/AgeChart.vue
  src/components/charts/BaseChart.js
  src/components/charts/ChartTab.vue
  src/components/charts/DayChart.vue
  src/components/charts/LineChart.js
  src/components/charts/MonthChart.vue
  src/components/sidebar/Urgent.vue
Labels: enhancement

#20 feat(settings): add dark mode support
  src/components/charts/ChartTab.vue
  src/components/sidebar/Settings.vue
  src/components/sidebar/SideBar.vue
  src/components/sidebar/Urgent.vue
Labels: enhancement

#21 bug(sw): disable service-worker
  src/registerServiceWorker.js
Labels: bug

#23 feat: responsive design.
  src/App.vue
  src/components/Dashboard.vue
  src/components/Footer.vue
  src/components/Report.vue
  src/components/charts/AgeChart.vue
  src/components/charts/DayChart.vue
  src/components/charts/MonthChart.vue
Labels: enhancement

#24 chore(readme): added README.md
  README.md
Labels: documentation, enhancement

#25 feat(graph): added new graphs and fixed data inconsistency
  src/components/AffectedPlaces.vue
  src/components/Dashboard.vue
  src/components/Footer.vue
  src/components/Report.vue
  src/components/charts/BaseChart.js
  src/components/charts/ChartTab.vue
  src/components/charts/DayChart.vue
  src/components/charts/MonthChart.vue
  src/components/charts/OverallChart.vue
  src/components/charts/TrendChart.vue
  src/components/sidebar/Settings.vue
  src/components/sidebar/SideBar.vue
  src/components/sidebar/Urgent.vue
Labels: bug, enhancement

#26 feat(changelo): added changelog tracker
  src/components/Dashboard.vue
  src/components/navbar/Changelog.vue
  src/components/navbar/NavBar.vue
  src/components/sidebar/Settings.vue
Labels: documentation, enhancement

#27 feat(analytics): added vue-analytics plugin for google analytics
  package-lock.json
  package.json
  src/main.js
Labels: enhancement

#28 refactor(analytics): use vue-tag instead of vue-analytics
  package-lock.json
  package.json
  src/main.js
Labels: enhancement

#29 feat(sidebar): added regions info
  src/components/Dashboard.vue
  src/components/Report.vue
  src/components/navbar/Changelog.vue
  src/components/navbar/NavBar.vue
  src/components/navbar/Settings.vue
  src/components/sidebar/Regions.vue
  src/components/sidebar/SideBar.vue
Labels: enhancement
